name: Run Selenium Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Clone Selenium Repo
        run: |
          set -x  # Enables command logging
          git clone https://github.com/baddipudiDebora/Combination-of-Single_Responsibility_Model_and_Strategy_DesignPattern_demo.git

      - name: Run Selenium Tests
        run: |
          set -x  # Enables command logging
          cd Combination-of-Single_Responsibility_Model_and_Strategy_DesignPattern_demo
          mvn test
