name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI repository
        uses: actions/checkout@v3

      - name: Clone the test repository
        run: git clone https://github.com/baddipudiDebora/Combination-of-Single_Responsibility_Model_and_Strategy_DesignPattern_demo.git

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Selenium IDE Runner
        run: npm install -g selenium-side-runner

      - name: Install Browser Drivers
        run: |
          npm install -g chromedriver
          npm install -g edgedriver
          npm install -g geckodriver

      - name: Install dependencies in test repo
        run: |
          cd Combination-of-Single_Responsibility_Model_and_Strategy_DesignPattern_demo
          mvn install

      - name: Run Selenium tests
        run: |
          cd Combination-of-Single_Responsibility_Model_and_Strategy_DesignPattern_demo
          mvn clean test
